#KAMS
kind: Deployement 
apiVersion: apps/v1
metadata:
  name: name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  strategy:
    type: Recreate 
  template: 
    metadata:
      name: hello
      labels: 
        app: hello
    spec:
      containers: 
      - name: helloword
        image: mylnadmarktech/hello:1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodeappsvc 
spec:
  selector:
    app: hello
  type: NodePort
  ports:
  - targetPort: 80
    nodePort: 31500
    port: 80
