#KAMS
kind: ReplicaSet 
apiVersion: apps/v1
metadata:
  name: nodapp
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      name: nodeweb-app
      labels:
        app: node
    spec:
      imagePullSecrets:
      - name: dockerhublogin
        
      containers:
      - name: nodeweb-app
        image: mylandmarktech/nodejs-fe-app
        ports:
        - containerPort: 9981
--- 
# Sercives 
apiVersion: v1 
kind: Service 
metadata:
  name: nodeappsvc
spec:
  selector:
    app: node
  type: NodePort
  ports:
  - targetPort: 5000
    nodePort: 31500 # 30000-32676
    port: 80

      
      

